version: "3.9"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/development/server/Dockerfile
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - db
    command:
      - wait-for-it.sh
      - db:3306
      - --timeout=60
      - --strict
      - --
      - air
      - -c
      - .air.toml
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: developer
      DB_PASSWORD: password
      DB_NAME: todo

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/development/web/Dockerfile
    volumes:
      - ./web:/web
    ports:
      - "3000:3000"
    tty: true

  db:
    container_name: db
    build:
      context: .
      dockerfile: ./docker/development/db/Dockerfile
    platform: linux/x86_64
    volumes:
      - ./docker/development/db/sql:/docker-entrypoint-initdb.d
      - ./docker/development/db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    tty: true
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
